name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS__SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/Frontend/frontend
          git pull https://github.com/Typerproject/Frontend
          cd ~
          docker-compose down
          docker-compose up --build -d
